### ISSUE TITLE
Maven install without tests causes file not found error

### ISSUE THREAD

**Issue by tobias-** [ebean-orm-tools/ebean-maven-tile#3]
When there are no tests compiled, the compilation fails with "File not found".

This can be caused by either src/tests/java being empty, or because maven is run with ```-Dmaven.test.skip=true```

Tested with version 2.4

**Comment by rbygrave** [comment]
Example error:
```console
[ERROR] Failed to execute goal io.ebean:querybean-maven-plugin:10.1.2:testEnhance 
  (io.ebean.tile:enhancement:2.4::test) on project example-java8: 
Error trying to transform classes: File not found /home/rob/github/examples-ebean/example-java8/target/test-classes/  
  currentDir:/home/rob/github/examples-ebean/example-java8/. -> [Help 1]
```

**Comment by tobias-** [comment]
That was quick! I'll be sure to include an example error message/stack whatever next time.

Thanks

**Comment by rbygrave** [comment]
*> I'll be sure to include an example error message/stack*

No worries.  I thought I'd just put it in to potentially help people doing
a google search for the error in the future etc.
