### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by javacraft** [ebean-orm-tools/ebean-maven-tile#5]
FYI. The README file does not reflect current information. It uses the older groupId rather than `io.ebean.tiles`. Furthermore, it does not reference a current or recent release, which I gather from Releases is now 5.5. The counterpart of this information on Ebean ORM site shows the correct groupId, but also uses an older release (2.9) 

Best regards,
frelling

**Comment by rbygrave** [comment]
Thanks, I've updated that now - closing.
